[BUGFIX] `argilla`: Prevent errors checking `Dataset` instances when `datasets` is not installed. (#5045)
<!-- Thanks for your contribution! As part of our Community Growers
initiative 🌱, we're donating Justdiggit bunds in your name to reforest
sub-Saharan Africa. To claim your Community Growers certificate, please
contact David Berenstein in our Slack community or fill in this form
https://tally.so/r/n9XrxK once your PR has been merged. -->

# Description

When datasets package is not installed, checks to identify if a list of
records is a `Dataset` instance fails:
```bash
File ~/Projects/argilla-io/argilla/argilla/src/argilla/records/_dataset_records.py:358, in DatasetRecords._ingest_records(self, records, mapping, user_id)
    356 if len(records) == 0:
    357     raise ValueError("No records provided to ingest.")
--> 358 if HFDatasetsIO._is_hf_dataset(dataset=records):
    359     records = HFDatasetsIO._record_dicts_from_datasets(dataset=records)
    360 if all(map(lambda r: isinstance(r, dict), records)):
    361     # Records as flat dicts of values to be matched to questions as suggestion or response

File ~/Projects/argilla-io/argilla/argilla/src/argilla/records/_io/_datasets.py:52, in HFDatasetsIO._is_hf_dataset(dataset)
     43 """Check if the object is a Hugging Face dataset.
     44
     45 Parameters:
   (...)
     49     bool: True if the object is a Hugging Face dataset, False otherwise.
     50 """
     51 HFDataset = _resolve_hf_datasets_type()
---> 52 return isinstance(dataset, HFDataset)

TypeError: isinstance() arg 2 must be a type or tuple of types
```

Thanks for reporting this, @maxserras  


**Type of change**

(Please delete options that are not relevant. Remember to title the PR
according to the type of change)

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes. And
ideally, reference `tests`)

- [ ] Test A
- [ ] Test B

**Checklist**

- [ ] I followed the style guidelines of this project
- [ ] I did a self-review of my code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my
feature works
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK)
(see text above)
- [ ] I have added relevant notes to the `CHANGELOG.md` file (See
https://keepachangelog.com/)