Merge from develop branch (#2445)
Still failing 4 tests. All failed tests are related to workspace
operations.

```bash
FAILED tests/client/test_api.py::test_dataset_copy_to_another_workspace - argilla.client.sdk.commons.errors.NotFoundApiError: Argilla server returned an error with http status: 404

FAILED tests/functional_tests/test_log_for_text_classification.py::test_log_data_in_several_workspaces - Exception: Wrong provided workspace my-fun-workspace
FAILED tests/functional_tests/datasets/test_delete_records_from_datasets.py::test_delete_records_without_permission - Exception: Wrong provided workspace argilla

FAILED tests/server/datasets/test_api.py::test_delete_records - assert 404 == 403
```


Running tests locally I found an error with DB rollback when a test is
failing. I've stopped using current seeds for tests (adding users).
Those users are created as a fixture where they are required. This
change affects to some users tests