opensearch docker compose file doesn't run
Following error is raised:
```
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.opensearch-dashboards.environment.DISABLE_SECURITY_DASHBOARDS_PLUGIN contains true, which is an invalid type, it should be a string, number, or a null
```

Changing `true` to 1 fixed the issue