opensearch docker compose file doesn't run (#2228)
# Description

Following error is raised:
```
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.opensearch-dashboards.environment.DISABLE_SECURITY_DASHBOARDS_PLUGIN contains true, which is an invalid type, it should be a string, number, or a null
```

<img width="994" alt="Screenshot 2023-01-18 at 14 42 09"
src="https://user-images.githubusercontent.com/42403093/213200977-5089c23f-187b-4944-8c35-63bf76d9f8b2.png">

Changing `true` to 1 fixed the issue

(Syntactic change to fix opensearch docker compose file)

**Type of change**

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)
- [ ] Documentation update