fix: Allow copy dataset with empty workspace to the default user workspace (#2618)
# Description

When users have an old dataset without workspaces (`-`) and try to
migrate to a proper workspace (the user default), an error is raised
with a 409 error:

```bash
AlreadyExistsApiError: Argilla server returned an error with http status: 409
Error details: [{'code': 'argilla.api.errors::EntityAlreadyExistsError', 'params': {'name': 'my_dataset', 'type': 'ServiceBaseDataset', 'workspace': 'argilla'}}]
```

This PR fixes this problem by checking the existence target workspace by
searching with provided name + workspace, instead of using a more wide
way.

**Type of change**

(Please delete options that are not relevant. Remember to title the PR
according to the type of change)

- [x] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested**

Tests checking this behavior are added.

**Checklist**

- [x] I have merged the original branch into my forked branch
- [x] follows the style guidelines of this project
- [x] I made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my
feature works